version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: course-selection-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: course-selection
    volumes:
      - mongodb_data:/data/db
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - course-selection-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: course-selection-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - course-selection-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: course-selection-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/course-selection?authSource=admin
      REDIS_URL: redis://:redis123@redis:6379
      JWT_SECRET: production-jwt-secret-change-this
      JWT_REFRESH_SECRET: production-refresh-secret-change-this
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - course-selection-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: course-selection-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3001/api/v1
    depends_on:
      - backend
    networks:
      - course-selection-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  course-selection-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local